# Generated by Django 4.1 on 2023-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateTimeField(verbose_name='Time sent')),
                ('subject', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=2048)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
